name: CI
on:
  #push:
   # branches: [ master ]
  workflow_dispatch:
  release:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 16
        
    - name: Install dependecies
      run: | 
            npm ci
            
    - name: Build for production
      run: |
            npm run build
      
    - name: Copy dist folder to server using scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "./dist"
        target: ${{ secrets.TEMP }}

    - name: Copy and cleanup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        script: |
          rm -rf ${{ secrets.TARGET }}/*
          cp -r ${{secrets.TEMP}}/dist/* ${{secrets.TARGET}}
          rm -rf ${{secrets.TEMP}}/dist
